version: "3"
services:
  tee3:
    build:
      context: .
      dockerfile: Dockerfile
      #args:
        #BUILD: 'local'
    image: tee3:1
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    links:
      - tee3_mysql
    depends_on:
      - tee3_mysql
    environment:
      APP_DEBUG: 'true'
      APP_KEY: base64:joUD24iQhw/uWEWR002FPF/QJrmL2NuNj3JKS0v9Hvc=
      DATABASE_URL: mysql://devuser:devpass@123.12.3.2/tee3
    networks:
      tee3_net:
        ipv4_address: 123.12.3.1

  tee3_mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tee3
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - 9906:3306
    networks:
      tee3_net:
        ipv4_address: 123.12.3.2
volumes:
  db_data: {}
networks:
  tee3_net:
    ipam:
      driver: default
      config:
        - subnet: 123.12.0.0/16
